# Generated by Django 5.0.4 on 2024-04-13 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0002_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
