# Generated by Django 5.0.4 on 2024-04-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0003_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/%y')),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=300)),
            ],
        ),
    ]
