# Generated by Django 5.0.4 on 2024-04-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0006_alter_comments_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.TextField(max_length=255),
        ),
    ]
