# Generated by Django 5.0.3 on 2024-04-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0007_alter_comments_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
